name: auto-gh-pages
on:
  push:
    branches:
    - main

jobs:
  main-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
    - name: checkout main
      uses: actions/checkout@v2
      with:
        ref: main

    - name: build main
      run: |
        npm install -g pnpm
        pnpm install
        pnpm build
        cp CNAME dist

    - name: push dist to branch gh-pages
      env:
        TOKEN: ${{ secrets.TOKEN }}
        REF: github.com/${{github.repository}}
        MYEMAIL: zane.deng@foxmail.com
        MYNAME: ${{github.repository_owner}}
      run: |
        cd dist
        git config --global user.email "${MYEMAIL}"
        git config --global user.name "${MYNAME}"
        git init
        git remote add origin https://${REF}
        git add .
        git commit -m "Updated By Github Actions With Build ${{github.run_number}} of ${{github.workflow}} For Github Pages"
        git branch -M main
        git push --force --quiet "https://${TOKEN}@${REF}" main:gh-pages
